packaging_format = 2

id = "earthstarserver"
name = "Earthstar Server"
description.en = "Run and configure an Earthstar server capable of syncing with other peers."
description.fr = "Exécuter et configurer un serveur Earthstar capable de se synchroniser avec d'autres pairs."

version = "0.1~ynh1"

maintainers = ["johanbove"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "LGPL-3.0-or-later"
website = "https://earthstar-project.org"
# demo = "https://demo.example.com"
# admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://earthstar-project.org/tutorials/run-a-server"
code = "https://github.com/johanbove/earthstarserver-ynh"
# optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, YunoHost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
# cpe = "???"
# optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
# fund = "???"

[integration]
yunohost = ">= 11.1.6"
# can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
architectures = "all"
multi_instance = true
# replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
ldap = "not_relevant" 
# replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
sso = "not_relevant"
# replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "75M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    # [install.path]
    # # this is a generic question - ask strings are automatically handled by YunoHost's core
    # type = "path"
    # default = "/example"

    [install.known_shares]
    ask.en = "Add the public addresses of the shares you'd like your server to replicate as a list of strings"
    help.en = "For example: \"+share1.abc123\", \"+share2.abc123\""
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "string"
    default = ""

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    # [install.language]
    # ask.en = "Choose the application language"
    # ask.fr = "Choisissez la langue de l'application"
    # type = "string"
    # choices = ["en"]
    # default = "en"

    # [install.admin]
    # # this is a generic question - ask strings are automatically handled by YunoHost's core
    # type = "user"

    # [install.password]
    # # this is a generic question - ask strings are automatically handled by YunoHost's core
    # # Note that user-provided passwords questions are not automatically saved as setting
    # help.en = "Use the help field to add an information for the admin about this question."
    # help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    # type = "password"

    [install.is_public]
    type = "boolean"
    default = true

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    # [resources.system_user]
    # # This will provision/deprovision a unix system user

    # [resources.install_dir]
    # # This will create/remove the install dir as /var/www/$app
    # # and store the corresponding setting $install_dir

    # [resources.data_dir]
    # # This will create/remove the data dir as /home/yunohost.app/$app
    # # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    # [resources.ports]
    # # This will pick a random port for reverse-proxying and store it as the $port setting 

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "node"